Playername = input("Welcome! What is your name?\n")
print("Let's get started,", Playername)
print("You will be asked to enter a series of words, which will form a little story for you\nEnjoy!\n") 
print("This is the intro to...\n")

Name1 = input("Enter a male full name:\n")
Adjective1 = input("Enter a superlative adjective: \n")
Occupation = input ("Enter an occupation:\n")
Place = input("Enter any place:\n")
Noun1 = input("Enter a noun (if you use an object, make it plural):\n")
Verb = input("Enter a past participle of a verb:\n")
Number = input("Enter a number: ")
Number = int(Number)
print(type(Number))
Noun2 = input("Enter a plural noun:\n")
Name2 = input("Enter a superhero name(could be made up):\n")
Adjective2 = input("Enter an adjective:\n")

print("\n")
print("My name is",Name1,"and I am the",Adjective1,"man alive.")
print("To the outside world I'm an ordinary ",Occupation,".",sep= "")
print("But seceretly, with the help of my friends (in/in a/at/in the) ",Place," I fight ",Noun1," and find others like me.\nI hunted down the man who ",Verb," my mother, but in doing so, I opened up the world to ",Number," new ",Noun2 , ".",sep = "")
print("I am ",Name2," and I am the only one ",Adjective2," enough to stop the ",Noun2,".",sep = "")
